import { MiscSDK } from "./misc";
import { singletonFunctionRegisrationFactory } from "components/utils";
const { registerFn } = singletonFunctionRegisrationFactory;

registerFn("getOtherSourceIncome", MiscSDK.getMiscVal("INCOME_SOURCE"));
registerFn("getResidentialStatus", MiscSDK.getMiscVal("RESI_STATUS"));
registerFn("getSalutation", MiscSDK.getMiscVal("SALUTATION_TYPE"));
registerFn("getProfessionalYears", MiscSDK.getMiscVal("PROF_YEARS"));
registerFn("getBusinessNature", MiscSDK.getMiscVal("BUSINESS_NATURE"));
registerFn("getFirmType", MiscSDK.getMiscVal("FIRM_TYPE"));
registerFn("getProfession", MiscSDK.getMiscVal("PROFESSION"));
registerFn("getProfessionYears", MiscSDK.getMiscVal("PROF_YEARS"));
registerFn("getProjectType", MiscSDK.getMiscVal("PROJECT_TYPE"));
registerFn("getExperianceyears", MiscSDK.getMiscVal("EXPERI_YEARS"));
registerFn("getPropertyType", MiscSDK.getMiscVal("PROPERTY_TYPE"));
registerFn("getGenderList", MiscSDK.getMiscVal("GENDER"));
registerFn("getRelationship", MiscSDK.getMiscVal("RELATIONSHIP"));
registerFn("getRetailEmployee", MiscSDK.getMiscVal("RETAIL_EMPL"));
registerFn("getUnsecuredEmployee", MiscSDK.getMiscVal("UNSECURED_EMPL"));
registerFn("getSMEEmployee", MiscSDK.getMiscVal("SME_EMPL"));
registerFn("getSMEBusinessEmployee", MiscSDK.getMiscVal("SME_EMPL_01"));
registerFn("getLoanPurpose", MiscSDK.getMiscVal("LOAN_PURPOSE"));
registerFn("getTypeOfLoan", MiscSDK.getMiscVal("TYPE_OF_LOAN"));
registerFn("getResidentialType", MiscSDK.getMiscVal("RESIDENCE_TYPE"));
registerFn("getBusinessPremise", MiscSDK.getMiscVal("BUSIN_PREMIS"));
registerFn("getInfraEmployee", MiscSDK.getMiscVal("INFRA_EMPL"));
registerFn("getEducationDtl", MiscSDK.getMiscVal("EDUCATION"));
registerFn("getSecurityOffered", MiscSDK.getMiscVal("SECURITY_OFF"));
registerFn("getYouAre", MiscSDK.getMiscVal("YOU_ARE"));
registerFn("getAccountType", MiscSDK.getMiscVal("ACCT_TYPE"));
registerFn("getChannelType", MiscSDK.getMiscVal("CHANNEL_TYPE"));
registerFn("getBusinessInterest", MiscSDK.getMiscVal("BUSI_INTREST"));
registerFn("getLeadPriority", MiscSDK.getMiscVal("LEAD_PRIORITY"));
registerFn("getIndividualAddressType", MiscSDK.getMiscVal("IND_ADD_TYPE"));
registerFn("businessAddressType", MiscSDK.getMiscVal("BUSSIN_ADD_TYPE"));
registerFn("facilityType", MiscSDK.getMiscVal("FACILITY_TYPE"));
registerFn("securityType", MiscSDK.getMiscVal("SECURITY_TYPE"));
registerFn("businessSize", MiscSDK.getMiscVal("BUSINESS_SIZE"));
registerFn("getNatureOfFacility", MiscSDK.getMiscVal("NATURE_FACILITY"));
registerFn("projectParticularType", MiscSDK.getMiscVal("PARTICULAR_TYPE"));
registerFn("bankFacilityType", MiscSDK.getMiscVal("ACCOUNT_TYPE"));
registerFn("getBankDocType", MiscSDK.getMiscVal("BANK_DOC_TYPE"));
registerFn("getITRDocType", MiscSDK.getMiscVal("ITR_DOC_TYPE"));
registerFn("getKYCDocType", MiscSDK.getMiscVal("KYC_DOC_TYPE"));
registerFn("getOtherDocType", MiscSDK.getMiscVal("OTHER_DOC_TYPE"));
registerFn("getGSTDocType", MiscSDK.getMiscVal("GST_DOC_TYPE"));
registerFn("getLeadStage", MiscSDK.getMiscVal("LEAD_STAGE"));
registerFn("getNomineeRelation", MiscSDK.getMiscVal("NOMINI_RELATION"));
